version: '3'

services:
  api-solid-pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=eteg
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespw